apiVersion: apps/v1
kind: Deployment
metadata:
  name: testproducer
spec:
  selector:
    matchLabels:
      app: testproducer
  template:
    metadata:
      labels:
        app: testproducer
    spec:
      containers:
      - name: testproducer
        image: shaunsimsimtech/testproducer:1.0.0
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: testproducer
spec:
  type: NodePort
  selector:
    app: testproducer
  ports:
  - port: 80
    targetPort: 15672
    nodePort: 32500
